[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://your-api-url.com"

[context.deploy-preview]
  NODE_ENV = "development"
  REACT_APP_API_URL = "https://your-api-url-staging.com"

[context.branch-deploy]
  NODE_ENV = "development"
  REACT_APP_API_URL = "https://your-api-url-dev.com"
